# Generated by Django 2.0.4 on 2018-04-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_u2f', '0004_auto_20170425_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='u2fkey',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
